module.exports = {
  rules: {
    'array-callback-return': [
      'error',
      {
        checkForEach: true,
      },
    ],
    'no-constructor-return': 'error',
    'no-duplicate-imports': [
      'error',
      {
        includeExports: true,
      },
    ],
    'no-promise-executor-return': 'error',
    'no-self-compare': 'error',
    'no-template-curly-in-string': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unreachable-loop': 'error',
    'no-unused-private-class-members': 'error',
    'no-use-before-define': 'error',
    'arrow-body-style': [
      'error',
      'as-needed',
      {
        requireReturnForObjectLiteral: true,
      },
    ],
    camelcase: 'error',
    'capitalized-comments': ['error', 'always'],
    'class-methods-use-this': 'error',
    'default-case': 'error',
    'default-case-last': 'error',
    'default-param-last': 'error',
    'dot-notation': 'error',
    eqeqeq: [
      'error',
      'always',
      {
        null: 'ignore',
      },
    ],
    'func-name-matching': ['error', 'always'],
    'func-names': ['error', 'never'],
    'func-style': ['error', 'expression'],
    'grouped-accessor-pairs': ['error', 'setBeforeGet'],
    'guard-for-in': 'error',
    'id-length': [
      'error',
      {
        min: 2,
        properties: 'never',
        exceptions: ['x', 'y', 'z'],
      },
    ],
    'init-declarations': ['error', 'always'],
    'max-classes-per-file': ['error', 1],
    'max-depth': ['error', 4],
    'max-nested-callbacks': ['error', 4],
    'max-params': ['error', 3],
    'multiline-comment-style': ['error', 'starred-block'],
    'new-cap': [
      'error',
      {
        newIsCap: true,
        capIsNew: false,
      },
    ],
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-console': 'error',
    'no-else-return': [
      'error',
      {
        allowElseIf: false,
      },
    ],
    'no-empty-function': 'error',
    'no-eval': 'error',
    'no-extra-label': 'error',
    'no-implicit-coercion': 'error',
    'no-implied-eval': 'error',
    'no-inline-comments': 'error',
    'no-iterator': 'error',
    'no-label-var': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 'error',
    'no-multi-assign': 'error',
    'no-multi-str': 'error',
    'no-negated-condition': 'error',
    'no-nested-ternary': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-object': 'error',
    'no-new-wrappers': 'error',
    'no-param-reassign': 'error',
    'no-proto': 'error',
    'no-restricted-globals': 'error',
    'no-return-assign': ['error', 'always'],
    'no-return-await': 'error',
    'no-script-url': 'error',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'no-undef-init': 'error',
    'no-undefined': 'error',
    'no-underscore-dangle': [
      'error',
      {
        allowAfterThis: true,
        enforceInMethodNames: true,
      },
    ],
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': 'error',
    'no-useless-call': 'error',
    'no-useless-computed-key': [
      'error',
      {
        enforceForClassMembers: true,
      },
    ],
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'no-warning-comments': 'error',
    'object-shorthand': ['error', 'always'],
    'one-var': ['error', 'never'],
    'operator-assignment': ['error', 'always'],
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-destructuring': [
      'error',
      {
        array: false,
        object: true,
      },
    ],
    'prefer-exponentiation-operator': 'error',
    'prefer-numeric-literals': 'error',
    'prefer-object-spread': 'error',
    'prefer-promise-reject-errors': [
      'error',
      {
        allowEmptyReject: true,
      },
    ],
    'prefer-regex-literals': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    radix: 'error',
    'spaced-comment': [
      'error',
      'always',
      {
        line: {
          markers: ['=', '!', '/'],
          exceptions: ['-', '+'],
        },
        block: {
          markers: ['=', '!', ':', '::'],
          exceptions: ['-', '+'],
          balanced: true,
        },
      },
    ],
    'symbol-description': 'error',
    yoda: ['error', 'never'],
    'line-comment-position': 'error',
    'lines-between-class-members': 'error',
    'padding-line-between-statements': [
      'error',
      {
        blankLine: 'always',
        prev: 'expression',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'expression',
      },
      {
        blankLine: 'never',
        prev: 'expression',
        next: 'expression',
      },
      {
        blankLine: 'always',
        prev: 'multiline-expression',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'multiline-expression',
      },
      {
        blankLine: 'always',
        prev: 'cjs-export',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'cjs-export',
      },
      {
        blankLine: 'always',
        prev: 'cjs-import',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'cjs-import',
      },
      {
        blankLine: 'never',
        prev: 'cjs-import',
        next: 'cjs-import',
      },
      {
        blankLine: 'always',
        prev: 'var',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'var',
      },
      {
        blankLine: 'never',
        prev: 'var',
        next: 'var',
      },
      {
        blankLine: 'always',
        prev: 'multiline-var',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'multiline-var',
      },
      {
        blankLine: 'always',
        prev: 'let',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'let',
      },
      {
        blankLine: 'never',
        prev: 'let',
        next: 'let',
      },
      {
        blankLine: 'always',
        prev: 'multiline-let',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'multiline-let',
      },
      {
        blankLine: 'always',
        prev: 'const',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'const',
      },
      {
        blankLine: 'never',
        prev: 'const',
        next: 'const',
      },
      {
        blankLine: 'always',
        prev: 'multiline-const',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'multiline-const',
      },
      {
        blankLine: 'always',
        prev: 'class',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'class',
      },
      {
        blankLine: 'always',
        prev: 'export',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'export',
      },
      {
        blankLine: 'always',
        prev: 'block-like',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'block-like',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'break',
      },
      {
        blankLine: 'never',
        prev: '*',
        next: 'case',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'continue',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'debugger',
      },
      {
        blankLine: 'never',
        prev: '*',
        next: 'default',
      },
      {
        blankLine: 'always',
        prev: 'directive',
        next: '*',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'directive',
      },
      {
        blankLine: 'always',
        prev: '*',
        next: 'throw',
      },
      { blankLine: 'always', prev: '*', next: 'return' },
    ],
  },
};
